name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-java:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      # Only run chmod on Unix-like OS
      - name: Grant execute permission for gradlew
        if: runner.os != 'Windows'
        run: chmod +x gradlew

      # Use the appropriate gradle wrapper for the OS
      - name: Build with Gradle
        run: |
          if [ "$RUNNER_OS" == "Windows" ]; then
            ./gradlew.bat build
          else
            ./gradlew build
          fi
        shell: bash

      # Only build & push Docker image on ubuntu-latest
      - name: Build and Push Docker Image
        if: matrix.os == 'ubuntu-latest'
        uses: mr-smithers-excellent/docker-build-push@v4
        with:
          image: nanajanashia/demo-app
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
